### PR TITLE
Board meeting notes

### PR DESCRIPTION
**Pull request by ryanmrichard**
The NWChemEx team had their first board meeting on 1/11/2024. This PR creates a post which provides a brief summary of the meeting. Board members are asked to read over the post and make sure I didn't miss anything.

### CODE REVIEW

**Review by hjjvandam — APPROVED** [review]
I think these notes accurately reflect what was said in the meeting.

**Review by jwaldrop107 — APPROVED** [review]
LGTM

**Comment by ryanmrichard** [comment]
Bump for @ajaypanyala and @wavefunction91

**Comment by ajaypanyala** [comment]
looks good!

**Review by ajaypanyala — APPROVED** [review]

**Review by wavefunction91 — APPROVED** [review]
Lgtm

**Pull request merged**
